apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:S77mebnEB4nOgED2LUGo0Q3CkkD5Zck8gdE6bmyo82g2AkYsaYKPlEqbVR4IW2u/duoDyVZJktzQMTlS4o1D0n1KKabAn6/ri2e9VyWOuZBH2Rt0NA7ksczlLIXnEQ/OAMsJU0vau8/zFfdgqbru4IGz1/zFCi7MgqxcrAP7FtFbqqJxDfvWN8tLDRxmrbk4ovOcl9cWktZCiXClzbaP+fbU0+MOlPZrvYHweTVo07y2TlofOMLIVgMKd3SV2RQEHxDuAoCKapXAmvpKSdXo/OLlhdz9b0YBfFDQSSsABtilKAsD4wJ/juMIGElhLE6r76SwDNfRqpojftsd6HNcki/rTpDtK34knIBZ0WnljnetgMiN2mJglhfHjASuTfKe,iv:bJSo9OCF/s1YHK/vDLWRiyPtS9lfwKGPUn2QbOJb0Jw=,tag:4Ns3ulOs5y0EUn3DPiXpZg==,type:str]
    identity.pub: ENC[AES256_GCM,data:4PSY62nY5X0M3Cc5XvNlVPdLX88QJlTCkMaGswT2h5TkMX8qsR5fSbW4SbW1pFV9c0n0lmXYvoO1NXvEQO7db+e6YYG63kiKcFbEZSjwgATiLXTKvp2wzrwDD3UaOqute7Zws0eblAbE/rCe0wBXulPiRmNGzmxa69Hsihfxrkd8yEIAszx305ZtRAIW1SeXTdx5idJuu2TnJw9j6unrJ8goP3AftWgz5V2oN/Uao+wFyhCZrwYlgvNItlMHLK5KcsGHxUU/yNSTNL53xg==,iv:0cCqD7ST8HD5gsYumyqguCLLaKYhxz7NDkd1UgVQqyw=,tag:ul2VAzUzY9cIm+898X8fkA==,type:str]
    known_hosts: ENC[AES256_GCM,data:0O27Qy8gwlrS0No/vafNDn4TDzR3gVlkFx+Hcma83ZqaT8M2s4DzMUY9ulgYRPZEdi7VmdSzW6YHh8DZNbBh5pjAYOfpT+IBDI5LWLZ/NP76kH84nO3kteYip8P+zfleQ/FMLSjezIHdM+TM/VLqkn7EG8X+CRfdUrqFNBC2oHXG3FTPTnlImIYzl43x2L3xyuz9y0GZpv1mbjVfxlvlR2UmvxV9ePmIjyoo,iv:bbAqXcWCDIe9AWodXCdIn7kKbT/6crmPkMbfja91GAY=,tag:ldp2NoCR3D1wLa49X9e5xg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1g224j6r5t2505qetn83njwkacr923zpu3hpmwwttu6h4xtdnx5qqav8lee
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxc3ByRHhEZnN0aHRWeXVo
            dy9pbFUrVlpVdXMwNFc1c0szNkVyVjBEbFhrCmVGeW5VbjcyZ0xXbGxuRXcxQmx1
            dHZZYU1aMkJvZU5JWWk0dnl1ZCt0dm8KLS0tIHpWeGtlNVl2ZC9zRVBEWWltZjNZ
            Z0dWOE0vUVBscnlNWFBvNUcxSlhTVVEK4p65/PPfo7FL5ED0qh8mhm/vX1stkjZ9
            V1c2skAEhRhGK2xRyp/w2bPnWYGs1Yk6DfNJuKGQu/tjVvHmAiF2EA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-08T09:33:33Z"
    mac: ENC[AES256_GCM,data:Xw/q5ujqe56m0QjbUBzm7QDhRtCERffJXkv03z0h+hS0FCZ74prJqqdSFfWNfpdCfJ49vJ2hHuLgXSFggEeMrT2mlY/Pil2idoLCbKzxLu6bCqWLH1QHTgGojenn55qtfwgvTUk7b/KDYjvljDucRB8YF8XhiCU/Qktd+8U8PJE=,iv:9U/D86Xs5irXpDMeHkRpqkPpt48TvVp8TL68Rfg+75c=,tag:PFIDgHXe3vKl4e6Y+UWrMg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
