apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:8iC3tjbYNWFSlW9lDkKj/ZMIKecNRW2SEVXsf2OppVhSJ0DNU4L/H0sKcMlb/omzwyWvRXV0XRXiEONlpUpBieVhdRgx6lKG+LbwyOq8kLEnrW3k0JEymOtw0OGQ3jSA9pLIVKhQFjhyDSfxLE0XEm4MpgYgXvRgEy/6MAcvojAWUzHZVEPQcc6RpoBg/hD/EBp78KQieeFTE7XBC7huPsG1EiLrkGi58kA6MPknoUd7AR9u9x91PnBC0bTEGQJVYSIbPiTBal//5kgP5df750twDOQdK/Z4BAlfovXr+StrCfpeaiYQ2lB72ZXfO9C2ltu1IajsZAb0fJIrIp0b0G9FzL1kVzYClznheipOPaZrTHPm+Ay5z+s5CLsF78AY,iv:+RBIW8Sa7qbNG7Z3IDr9iVdPuWs9AECppBD0ycMawBI=,tag:4+/K7ndKvab2lCsqzxVhAQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:WJzg2XrASPcDHU3WfgLnxnNKrqbzW18qw5Ifs0GGQ0KWrmGSWr4j4xKQhfv2deshNp1u6uJTXWIBatEOYnUhWFYQAefgbAMV0qP1sHpW0pym+Y6lFtf51nNW8T+0p/wHf5mkNNAP7fEBwfDOC4Hq3oXEE61p5Ha85s8ARGl48X9rfsHZPO9wZHVK7UEOnsdAzY7dFoygeRdXzU3Vt9T5n/77mG5sWuZOXJOM9Ue9tU8Esk+RLGvfn1QN4QpY6NSc9rzKLIWSRn5TSr8kYw==,iv:BfNjhWdIgfCl2tDCHRXDyN/I2WqWdElIFo0odJGK2BQ=,tag:YXV+lhO3U52btsP4RzciRA==,type:str]
    known_hosts: ENC[AES256_GCM,data:mJ3PfKLuDvsq57eIPiMV4k5FLjL91zQDHGDjcklQKRR2dWm14Zxea3/eyORMhlea00+duPliVfeCQcMa+H2O5hoj3OAfcve53XX3ZFWtFVQLF3h9jeRHrMMMFTZNOUazah2sG2eMTeYIgfJH+kto1aG5KBL7tBXD8fcNNLKJQuUYX4I95MXQ5sYbk+IzrPVRvxDsQGy1UFqfgrIQAuDF3ReqSj3uFC/UMzVO,iv:TPSmQeoOz/gf3O18nXPyDVBC+WhEarpymf0JNsoVQHg=,tag:yOud5xKS7QaiZPy1122hYw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1g224j6r5t2505qetn83njwkacr923zpu3hpmwwttu6h4xtdnx5qqav8lee
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcE5rdUt1R2tkbFl2c05v
            SDBQZWc1L2g5MGc3OExTeUptSXdzZmUvUXpJCnRaZHhWWmowOGhIanhWMDZFcFF0
            T1o0WlBOQTJkN29RTkhNSURZUHVENEkKLS0tIEhpT3grb1ZyT0NheElUUENud25t
            TkVzZ0h1b3dmRFY1K3ZHOGJRMXZtQ2cK8Th/U1YtVNPKFgxRHvflq/yTEvh/OdgS
            s+iKEDZ0wVyBQA6OadEV7m28h5w4R5GFQR52SEeD9IxOTKMkmxIJsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-07T21:00:10Z"
    mac: ENC[AES256_GCM,data:BUtUqlMdm6oj6e/Nel3Go22p3g0QSTpeip0WsnIobC0VjxRU0N0lE0kEAheV3qGWewi4QmtJ3iRdtmWJFvsRTB76U86LolYtkSyuO2mS84nSdAqOixOtvzIoCijI13JNkzP2MJf/UY4PFCw/SCBXbE5tM7b1WDjwyB/8wwZa8Q4=,iv:GHzxC0NUVfaT2Owhc4SAVdeZvsGH9Mt8suik0M7Wdrs=,tag:t75iA6fLdYqx3SxqH28Sqg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
